### ISSUE TITLE
Rclone cache size

### ISSUE THREAD

**Issue by mahogl** [kelinger/OmniStream#17]
Hi again, 

Quick question is there a way i can adjust the vfs-cache-max-size in the configuration? I can`t find any reference to where it it is configured. My server is running with at 233GB SSD drive, and it can be a bit tight there sometimes when a lot of files are downloading at the same time.

Best regards,
Marius

**Comment by kelinger** [comment]
Yes; we didn't document this because it can get you into trouble if you don't know what you're doing but we did add the ability to override the defaults for users like you.  First, take down OmniStream completely:

`omni down`

Then go into your configs for OmniMount
`omni configs`
`cd omnimount`

Create a file called "vfs.conf" with your favorite editor (eg, vi, nano)
`nano vfs.conf`

Finally, add any or all of the following variables and set them as you wish.  I've included the defaults here that OmniStream uses if they are not defined.  Note that there isn't a lot of error checking here so if you tell it to create a 68 TB cache, it will certainly try but don't expect miraculous results.

```
VFSMAX=100G
VFSAGE=48h
VFSPOLL=5m
VFSREAD=2G
VFSCACHE=yes
```
The last parameter can be used to disable caching altogether.

When finished, you can bring OmniStream back up:

`omni up`

and it should be using your new parameters.

--Ken

**Comment by mahogl** [comment]
Perfect! Thank you, for the quick response :)

**Comment by kelinger** [comment]
No problem!  Responses are easy when the work has already been done!
