### ISSUE TITLE
After Update Omnimount is unhealthy

### ISSUE THREAD

**Issue by DPMUC** [kelinger/OmniStream#18]
Hey guys - After the latest Update my omnimount Container is showing „unhealthy“ and so in doesnt work anymore…
Omni repair does not help… any suggestion? :)
Greets

**Comment by DPMUC** [comment]
Sorry my fault… - After omni Update it worked again… 🙈

**Comment by klinger-cpi** [comment]
There was an update to OmniMount (the Docker container) as well as OmniStream (this project) today in order to make the the cloud mounts more stable and resilient in the long term.  Of course, this update triggered a restart of OmniMount which then restarted everything dependent on it.  However, once up, you should now have all the benefits of these changes.

To anyone bystanders experiencing this:  if you don't see a recovery in a few minutes on its own, simply run:
`omni down`
`omni up`
