### ISSUE TITLE
Server HDD full

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#41]
Hi guys,

I had an issue where my HDD got full. Everything stopped working, so I restored from a backup.

Now everything is back online, except my plex database is gone. The Plex settings are still there, but the directories/database was missing. I migrated from Gooby, and did the backup through omni - which may have been the cause?

Anyway. Im okay with the database, Ill just let it run and ratelimit me for a few weeks until done lol. Now for my question - is there any way to make a script to delete completed downloads so I dont run out of disk again?

Thanking you

**Comment by kelinger** [comment]
Completed downloads (those that download completely and have successfully been uploaded to the cloud) are removed upon copying to the cloud.  What still needs to be removed are incomplete or errored-out downloads.  If you use SABnzbd, for example, a download that could not be repaired remains locally stored since it cannot be decompressed, but there may (in theory; I have yet to see it happen) be a chance that the missing parts are available in the near future.

If you use Radarr/Sonarr/*arr they also show unprocessed downloads (these may be complete or incomplete but, for one reason or another, they couldn't be matched successfully to the movie/show/album).  These also remain in your downloads until you manually process them from the corresponding *arr.  For example, a TV episode may be misnamed so Sonarr can't tell that it is "The Simpsons, S03E15."  Once you fix that mapping in Sonarr, the download will process, pop out of Sonarr's queue, and be queued for upload to the cloud and removal from the local storage.

**Comment by falcomm6** [comment]
Thank you. Will follow your steps.
