### ISSUE TITLE
space issues

### ISSUE THREAD

**Issue by falcomm6** [kelinger/OmniStream#42]
Hi guys,

I love the new OmniStream, im just having some continued issues with space for some reason. I thought it was due to misconfigured sabnzbd, but now ive tried migrating from gooby with nzbget and still having it. 

Ive tracked down a lot of data being saved in var. Im not good at linux but i was able to track a good amount of data in var at the below directory. Ive had 500gb full disk twice in 2 weeks, where i never had this issue with Gooby. Any tips?

<img width="429" alt="space" src="https://user-images.githubusercontent.com/67247329/214436905-e6835f91-e52b-4bd7-bf58-cb9aa7244756.png">

it doesnt let me cd to docker from this location to dig deeper for some reason.

**Comment by kelinger** [comment]
This may be an easy one:  we're not storing anything specifically for OmniStream's code in /var.  But, I'm sure Docker is.  If you don't regularly run `omni update` then Docker will be keeping older copies of containers around (eg, you're running Sonarr and a newer container comes out, that will be downloaded and installed but the previous container remains locally cached by design).  Some commands may help.  Note that there is no need to run more than one of these:

`omni update` - updates the code base, downloads any newer containers that weren't previously cached, swaps out the old for the new, and then purges all non-used containers.  If there are a lot, this may seem to hang for a minute at the end of the update but trust me... you'll see a bunch of data scroll by and a summary of how much space was reclaimed when it's finished.

`omni rebuild` - same as above without the update portion

`omni clean` - very brute force.  This takes down everything and then purges all containers--old and new.  It does not delete any of your configs, data, personal shares, etc. but basically leaves you with a clean system and OmniStream still installed but not running.  Like the above, it will display the amount of space reclaimed.  Unlike the others, you will need to start OmniStream when finished (if you wish) and this will redownload all containers that are enabled.  I want to reiterate that this will not destroy any personalization or customization but it should be followed by `omni up` when you're ready for things to start running again.

**Comment by kelinger** [comment]
Additional notes:

Depending on what you're running, some container publishers have daily updates or even multiple updates per day.  The "watchtower" container keeps an eye on these and predownloads them so the next `omni update` can just swap out the old and replace it with the new with minimal downtime (in most cases, the swap is a "blimp" and only noticeable if you're actively using the specific container--or a dependency--when it is switched over).

I personally give my system an `omni update` everytime I log in just to a) make sure I'm on the latest and greatest and b) clear out the previously used containers.  It usually only takes a minute and I can control when I do it (ie, not while a spouse is watching a movie on Plex).

**Comment by falcomm6** [comment]
Thanks for this. Looks to still be 100GB, not entirely sure whats going on. Maybe im saving something somewhere I shouldnt.

Do you know how I can navigate to the docker folder? right now it  says I cannot cd there, perhaps its mounted and lives elsewhere. Curious  to see exactly whats happening.

**Comment by kelinger** [comment]
You probably need to use sudo.

`sudo -s` will start a shell essentially as root.  Then you can `cd` anywhere you want and you don't need to use sudo again for things like `du` when you try to find the culprit.  When done, type `exit` to return to your peon-level non-root login 😄

**Comment by falcomm6** [comment]
LOL. I definitely need to stay peon level as much as possible. Here is what im getting. I tried -s and it didnt help me either. 

![image](https://user-images.githubusercontent.com/67247329/214443985-e0155968-cb81-455f-93f4-e75d98eb48a4.png)

**Comment by falcomm6** [comment]
NVM I got it now. Thank you so much for helping this peon! lol

**Comment by falcomm6** [comment]
Is this normal? All the data is in overlay

![image](https://user-images.githubusercontent.com/67247329/214444360-0cfb0717-12eb-42d8-81fb-6aa14353fc04.png)

![image](https://user-images.githubusercontent.com/67247329/214444409-b1a1ffa1-3fd0-4bff-b8b1-41c7e7c37281.png)

**Comment by falcomm6** [comment]
I cleaned a LOT using something I foung on Google. Below deleted the volumed which were not running. Extra 100gb. Time will tell if I broke something lol.

docker volume rm $(docker volume ls -qf dangling=true)

Thanks!
