### ISSUE TITLE
Plex not secure with Traefik

### ISSUE THREAD

**Issue by christeasdale** [kelinger/OmniStream#55]
This seems to still be an issue with Traefik [Plex not Secure](https://forums.plex.tv/t/traefik-reverseproxy-remote-accsess-red-but-available-remotly/694506) Media being played back on all clients does not show as secure in Plex.  Certain clients will fail playback with this.  In Gooby with Nginx this wasn't an issue.  Are others seeing this issue?  Are there any solutions?

**Comment by kelinger** [comment]
Are you connecting to Plex via the Traefik proxy or did you open up a port and connect to Plex directly?

Unless you've changed from the defaults, the Plex server should be setup with remote access looking like this:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/11468127/228740013-a6bac901-d94f-4250-b291-71a116868b97.png">

The public IP is your host server's IP address and 443 tells it to route through Traefik.  I connect to my Plex server this way using https://plex.mydomain.com (no need to specify the port since 443 is implied by https).

Now, the top part will often say "unreachable" but that's because Plex doesn't know that Traefik exists.  But that's OK.

You'll also want to configure the "customer server access URL" on the network tab of settings (towards the bottom).  Again, if setup using the defaults, this would just be https://plex.mydomain.com.

Since all access to and from Plex is going through https, it is indeed secure.

**Comment by christeasdale** [comment]
Setup with all the defaults exactly as you mention above:

![Default](https://user-images.githubusercontent.com/29345366/228749110-49709c32-063e-46cb-bc11-521cbbebaa78.PNG)

Modifying plex yaml to open a port for Plex and not connecting through traefik:

![Open Port](https://user-images.githubusercontent.com/29345366/228749429-064796c3-ab71-44f6-a379-eb8932ff67c4.PNG)


I think indeed it is technically secure but Plex/Plex servers don't think so.   So configured with Traefik if you change inside Plex settings from Secure Connection : preferred to required nothing will work and you can't connect to Plex server.  Also some Plex clients will fail playback (Namely Android TV, FireTV) if the connection isn't secure.  Interestingly this was not an issue with NGINX in Gooby.

**Comment by thunderstorm654** [comment]
> Setup with all the defaults exactly as you mention above:
> 
> ![Default](https://user-images.githubusercontent.com/29345366/228751258-c2d7b30f-5a72-426f-bb7d-60badefef891.PNG)
> 
> Modifying plex yaml to open a port for Plex and not connecting through traefik:
> 
> ![Open Port](https://user-images.githubusercontent.com/29345366/228751315-5ac4ec3e-81e7-46d2-a343-95baf53ed471.PNG)
> 
> I think indeed it is technically secure but Plex/Plex servers don't think so. So configured with Traefik if you change inside Plex settings from Secure Connection : preferred to required nothing will work and you can't connect to Plex server. Also some Plex clients will fail playback (Namely Android TV, FireTV) if the connection isn't secure. Interestingly this was not an issue with NGINX in Gooby.

I'm seeing the same behaviour as you with the red arrows and remote access error (expected) though I hadn't noticed any issues with client playback so to be honest hadn't questioned it!

**Comment by christeasdale** [comment]
One of my family members uses ubiquiti equipment and they would get playback fail on FireTV  when I was running Gooby but adding port to "customer server access URL" from  https://plex.mydomain.com to https://plex.mydomain.com:443 fixed it on Gooby and plex had green arrows and he had no more problems.  Now problems are back with OmniStream and adding 443 doesn't help with traefik.  Don't change Plex setting to require secure connections on remote sever you will lose access and have to ssh tunnel into your sever to access it again.  Maybe there is a way to change traefix to fix this ... I am no expert.

**Comment by christeasdale** [comment]
This post seems to be a [possible solution](https://www.reddit.com/r/PleX/comments/ql93s9/insecure_connection_because_of_reverse_proxy/?utm_source=share&utm_medium=web2x&context=3l)?  Seems connection from Plex docker to traafik might be the issue?  I am noob on Traefik can someone guide me here and I will do the work to test this?  thanks

**Comment by Simmy-Simalia** [comment]
Has anyone remedied this error? I've tried a few things but to no avail.

**Comment by kelinger** [comment]
There really isn't any issue here.  https to Traefik = secure.  Traefik to Plex is happening on the same server and is literally two areas of memory communicating with each other (whether encrypted or unencrypted).  Plex may not "think" it is secure because it sees this data exchange and not the exchange between the true client (Plex's app or Infuse or a web browser) and Plex.
