### ISSUE TITLE
Access to omnimount image prior to :latest

### ISSUE THREAD

**Issue by rkdavies** [kelinger/OmniStream#69]
Something broke about 3 weeks ago in our OmniStream stack. I'm not sure if it is related to the upgrade to omnimount dockerhub image or not, but I'm looking to roll-back that component to see if our latency to gDrive goes away. 

Any help would be appreciated. Thank you in advance.
Robert

**Comment by jaseelye** [comment]
Would be nice to be able to address older versions. Can you please add the tags? Omnimount only has latest, arm64 and beta.

**Comment by kelinger** [comment]
Folks, I'm really sorry about this.  I recently migrated my files from Google to local storage and had issues with OmniMount.  I made the changes necessary and it seemed to work across the board.  Apparently, this is not the case.  The change was to the `dir-cache-time` setting (going from 96h to 10s) as the directory caching didn't seem to work correctly with the NFS or SMB mount to my NAS (when set to 96h).

So the obvious fix here is to make that a variable rather than being hardcoded.  This is where the second problem starts:  in my hasty exodus from cloud storage and hosting, I lost the source for OmniMount (OmniStream itself is in GIT but OmniMount never was).  Now, it's not a complex project so recreating it shouldn't be TOO hard.  But, it also means that I have to ensure it works 100% with the way OmniStream was designed since we don't want to have any changes that require another setup process or attempt to migrate from an old to a new config.

I'm working on this now and was hoping to have it released sooner.  My day job got in the way, though.  I'm hoping to have a fix soon, though.

For those technically inclined, you can fix this by entering the "omnimount" container and editing this setting in the "omni-rclone" script.  Just switch the 10s back to 96h on `--dir-cache-time 10s` line.

**Comment by mahogl** [comment]
@kelinger i am also in the process with switching to local nas nfs storage, when you have some spare time could you give an update on how you did make it work

I am trying with the local storage option I rclone, but for some reason the share shows up empty when I change the rclone config and media folder true omni menu.

Thanks again for your time.

**Comment by kelinger** [comment]
First things first:

@rkdavies @jaseelye  could you try an `omni clean` and finally `omni up`?  I've just posted a new OmniMount.  You should see in `omni logs omnimount` (after it is up) additional variables that are set at runtime and are equal to what OmniMount used to use.  In other words, this should be working for you now.

**Comment by jaseelye** [comment]
@kelinger thank you! It looks to be working like it did before.

**Comment by rkdavies** [comment]
I can confirm that directory traversal is snappy again, and media playback is back to its former glory!

Thank you!
