### ISSUE TITLE
Omnimount instability

### ISSUE THREAD

**Issue by shadowsbane0** [kelinger/OmniStream#9]
I’m having an issue with omnimount restarting. When it does Plex and Emby loose their connection to the mount point but don’t pick it back up when omnimount comes back online. I have to reboot both Plex and Emby for it to pick back up the Media mount. It happens on a fairly routine basis. There isn’t anything in the log as to why omnimount is restarting.

Things on my end that can play a factor but are uncertain. I have rclone tweaked to give me two mounts. This is because I want to still be able to stream my content while at the same time  I move my content away from big G. To wit, I have rclone set with two remotes. Remote 1 services my media streaming only. Remote 2 has my full access credentials while I’m transferring 45TB of content down from big G to my own bare metal systems. I can’t say for certain if this is causing an issue with omnimount (Any sort of timing issue).  My downstream connection is pretty well saturated (shouldn’t be according to talks with ISP but reality wins). I still have roughly another week and a half of downloading before I’m on my own local source.

Once this downloading is complete I’ll be moving to Proxmox for my host system and virtualize my media content. I have work related services that I would like to keep separate that (hat tip!) I’ll use your OmniStream framework as a template. Should my endeavor prove profitable I’ll certainly pass thru the monetary credits you deserve.

Overall I’m extremely pleased with the work you and @TechPerplexed are doing. It is really awesome and has opened me up to an entire ecosystem I had previously not known. I love learning and experimenting with new things - so a heartfelt thank you to both of you!

**Comment by shadowsbane0** [comment]
I’ll check it when I get home later. Yes my issue is as you described.

Sent from my iPhone

On Mar 30, 2022, at 1:01 PM, Ken Linger ***@***.***> wrote:

﻿

This was a known issue a few weeks ago that I believe I fixed. Can you confirm you are using the latest versions of both OmniMount and OmniStream?

The problem I saw before was related to containers keeping their mounts to “OmniMount” but the actual mounts within OmniMount were failing. The end result was a mount in programs like Plex which passed the “is it mounted?” test but were effectively empty (they were seeing the Docker mount, not the Rclone mount that was passed through). This was fixed via a series of healthcheck updates and some updates to OmniMount itself.

While an “omni update” should suffice, you may want to just do an “omni down” followed by a “git pull” within the $OMNIHOME followed by another “omni up.” This is because some of the updates downloaded take one cycle to fully apply their changes (not sure about this; that was an issue early on and I can’t remember if I fixed that; this way, we can avoid a few “ok, try again” back and forths).

**Comment by shadowsbane0** [comment]
It’s my setup. Looking at the Omnimount log I see that it doesn’t know what to do with the extra remote statement in the rclone.conf file that I have for my file transfer. It will go away when I’m done but I don’t know if future users will have more than one rclone remote. Omnimount is issuing a shutdown command and restarting.

Sent from my iPad

On Mar 30, 2022, at 13:01, Ken Linger ***@***.***> wrote:

﻿

This was a known issue a few weeks ago that I believe I fixed. Can you confirm you are using the latest versions of both OmniMount and OmniStream?

The problem I saw before was related to containers keeping their mounts to “OmniMount” but the actual mounts within OmniMount were failing. The end result was a mount in programs like Plex which passed the “is it mounted?” test but were effectively empty (they were seeing the Docker mount, not the Rclone mount that was passed through). This was fixed via a series of healthcheck updates and some updates to OmniMount itself.

While an “omni update” should suffice, you may want to just do an “omni down” followed by a “git pull” within the $OMNIHOME followed by another “omni up.” This is because some of the updates downloaded take one cycle to fully apply their changes (not sure about this; that was an issue early on and I can’t remember if I fixed that; this way, we can avoid a few “ok, try again” back and forths).

**Comment by shadowsbane0** [comment]
Oh, BTW ovpn is discontinued according to their page on docker hub. I personally use expressvpn and found a container for it that I’m going to try out. I’ll post my results here. I can still fall back to my delugevpn yaml from before that was working well for me. I have deluge intentionally unconfigured right now until my file transfer is complete. I don’t want anything new being added that might get missed in the transfer.

I mostly need to figure out the docker-compose part. The compose file creates it as a service (probably have an issue with how Omninet is scripted) then there is an example of pulling a container that will use service in the same yaml. Am I supposed to nest my whole server yaml config for my operating container in the expressvpn service yaml or just the initial info and still have my full server yaml for docker-compose?

Sent from my iPad

On Mar 30, 2022, at 13:01, Ken Linger ***@***.***> wrote:

﻿

This was a known issue a few weeks ago that I believe I fixed. Can you confirm you are using the latest versions of both OmniMount and OmniStream?

The problem I saw before was related to containers keeping their mounts to “OmniMount” but the actual mounts within OmniMount were failing. The end result was a mount in programs like Plex which passed the “is it mounted?” test but were effectively empty (they were seeing the Docker mount, not the Rclone mount that was passed through). This was fixed via a series of healthcheck updates and some updates to OmniMount itself.

While an “omni update” should suffice, you may want to just do an “omni down” followed by a “git pull” within the $OMNIHOME followed by another “omni up.” This is because some of the updates downloaded take one cycle to fully apply their changes (not sure about this; that was an issue early on and I can’t remember if I fixed that; this way, we can avoid a few “ok, try again” back and forths).

**Comment by kelinger** [comment]
This was a known issue a few weeks ago that I believe I fixed.  Can you confirm you are using the latest versions of both OmniMount and OmniStream?

The problem I saw before was related to containers keeping their mounts to “OmniMount” but the actual mounts within OmniMount were failing.  The end result was a mount in programs like Plex which passed the “is it mounted?” test but were effectively empty (they were seeing the Docker mount, not the Rclone mount that was passed through).  This was fixed via a series of healthcheck updates and some updates to OmniMount itself.

While an “omni update” should suffice, you may want to just do an “omni down” followed by a “git pull” within the $OMNIHOME followed by another “omni up.”  This is because some of the updates downloaded take one cycle to fully apply their changes (not sure about this; that was an issue early on and I can’t remember if I fixed that; this way, we can avoid a few “ok, try again” back and forths).



From: shadowsbane0 ***@***.***>
Date: Tuesday, March 29, 2022 at 8:13 PM
To: kelinger/OmniStream ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kelinger/OmniStream] Omnimount instability (Issue #9)

I’m having an issue with omnimount restarting. When it does Plex and Emby loose their connection to the mount point but don’t pick it back up when omnimount comes back online. I have to reboot both Plex and Emby for it to pick back up the Media mount. It happens on a fairly routine basis. There isn’t anything in the log as to why omnimount is restarting.

Things on my end that can play a factor but are uncertain. I have rclone tweaked to give me two mounts. This is because I want to still be able to stream my content while at the same time I move my content away from big G. To wit, I have rclone set with two remotes. Remote 1 services my media streaming only. Remote 2 has my full access credentials while I’m transferring 45TB of content down from big G to my own bare metal systems. I can’t say for certain if this is causing an issue with omnimount (Any sort of timing issue). My downstream connection is pretty well saturated (shouldn’t be according to talks with ISP but reality wins). I still have roughly another week and a half of downloading before I’m on my own local source.

Once this downloading is complete I’ll be moving to Proxmox for my host system and virtualize my media content. I have work related services that I would like to keep separate that (hat tip!) I’ll use your OmniStream framework as a template. Should my endeavor prove profitable I’ll certainly pass thru the monetary credits you deserve.

Overall I’m extremely pleased with the work you and @TechPerplexed<https://github.com/TechPerplexed> are doing. It is really awesome and has opened me up to an entire ecosystem I had previously not known. I love learning and experimenting with new things - so a heartfelt thank you to both of you!
